### ISSUE TITLE
Plan for release 0.1.9

### ISSUE THREAD

**Issue by miikka** [bensu/doo#169]
Hey, I have again a bit of time for this project, so I'd like to merge some of the PRs that look ready, and then I'd like to create a release. Specifically:

* [x] First, fix the CI services: #167, #168
* [x] Add support for headless Firefox #160 
* [x] ~Add support for karma-coverage #125~ Postponed.
* [x] ~~There's no PR yet, but fixing #163 should be straightforward.~~ PR #170.
* [x] Custom Karma configuration: #108, #171, maybe even #165?
* [x] Bonus PR that appeared just at the right time: Fix symbol quoting in Doo config: #172

**Comment by miikka** [comment]
Change of plans: merged #108, which also addresses #43. Not sure yet what to do with #125.

**Comment by miikka** [comment]
Now on Clojars: `[lein-doo "0.1.9"]`
